import os
from pynput.keyboard import Key, Controller
import time
import pyautogui as p

# time.sleep(3)

keyboard = Controller()

os.startfile('notepad.exe')
p.countdown(2)
with keyboard.pressed(Key.cmd):
    keyboard.press(Key.up)
    keyboard.release(Key.up)
p.write("<!DOCTYPE html>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("<html>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("<head>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("<title>Web page</title>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("</head>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("<body>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("<h1>Welcome</h1>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("</body>")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
p.write("</html>")
p.countdown(1)
with keyboard.pressed(Key.ctrl):
    keyboard.press("s")
    keyboard.release("s")
p.countdown(1)
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
p.countdown(1)
keyboard.press(Key.down)
keyboard.release(Key.down) 
keyboard.press(Key.down)
keyboard.release(Key.down) 
p.countdown(1)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
keyboard.press(Key.tab)
keyboard.release(Key.tab) 
p.write("pythonhtml.html")
keyboard.press(Key.enter)
keyboard.release(Key.enter)
with keyboard.presses(Key.alt):
    keyboard.press(Key.tab)
    keyboard.release(Key.tab) 

print("done")